(define (cont-frac n d k)
  (define (cal i)
    (if (> i k)
  0
  (/ (n i) (+ (d i) (cal (+ i 1))))))
(cal 1)) 
(define (cont-frac1 n d k )
(define (cal i tans)
(if (< i 1)
  tans
  (cal (- i 1) (/ (n i) (+ (d i) tans))) 
  )
)
(cal k 0.0)
)
(define a (cont-frac1 (lambda (i) 1.0)
       (lambda (i) 1.0)
       12)) 
(/ 1 a)
