(define (cont-frac n d k)
  (define (cal i)
    (if (> i k)
  0
  (/ (n i) (- (d i) (cal (+ i 1))))))
(cal 1)) 
(define (mytan x)
  (define (n i)
    (if (= i 1) x (square x)))
  (define (d i)
    (- (* i 2) 1.0)
    )
  (cont-frac n d 100)
  )

(newline)
(display (mytan 3.14159))
(newline)
(exit)
