(define (make-point x y) (cons x y))
(define (x-point t) (car t))
(define (y-point t) (cdr t))
(define (make-segment a b) (cons a b))
(define (start-segment t) (car t))
(define (end-segment t) (cdr t))
(define (midpoint-segment t)
  (make-point (/ (+ (caar t) (cadr t)) 2) (/ (+ (cdar t) (cddr t)) 2)))
(define (print-point p)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (newline))
(define p1 (make-point 1 2))
(define p2 (make-point 3 4))
(define s1 (make-segment p1 p2))
(print-point (midpoint-segment s1))

