(define (make-point x y) (cons x y))
(define (x-point t) (car t))
(define (y-point t) (cdr t))
;(define (make-rect p1 p2) (cons p1 p2))
;(define (width-rect a) (- (cadr a) (caar a)))
;(define (height-rect a) (- (cddr a) (cdar a)))
(define (make-rect p1 p2)  (cons p1 (cons (- (car p2) (car p1) ) (- (cdr p2) (cdr p1)))))
(define (width-rect a) (cadr a))
(define (height-rect a) (cddr a))
(define (perimeter-rect a) (* 2 (+ (width-rect a) (height-rect a))))
(define (square-rect a) (* (width-rect a) (height-rect a)))
(define a (make-rect (make-point 1 2) (make-point 3 5))) 
(perimeter-rect a)
(square-rect a)
