(define (mycons x y) (* (expt 2 x) (expt 3 y)))
(define (mycar a)
  (if (= 0 (remainder a 2))
    (+ 1 (mycar (/ a 2)))
    0))
(define (mycdr a)
  (if (= 0 (remainder a 3))
    (+ 1 (mycar (/ a 3)))
    0))
(define a (mycons 5 6))
(mycar a)
(mycdr a)
