(display x)
(define (mystery x)
  (define (loop x y)
    (display x)
    (display #\space)
    (display y)
    (newline)
    (if (null? x)
      y
      (let ((temp (cdr x)))
       (set-cdr! x y)
       (loop temp x))))
  (loop x `()))
(set! v `((x (y z)) b (t s)))
(define w (mystery v))
