(define (rand x)
  (define (generate)
    (set! x (rand-update x))
    x)
  (define (reset new-value) 
    (set! x new-value))
  (define (dispatch opt)
    (cond ((eq? opt `generate) generate)
          ((eq? opt `reset) reset)
          (else (error "Unknown request --rand")))))
